spring:
  datasource:
    url: jdbc:postgresql://burndown-postgres:5432/burndown_db
    username: postgres
    password: root
  data:
    redis:
      host: localhost
      port: 6379

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
      probes:
        enabled: true
  metrics:
    tags:
      application: burndown-management
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.9,0.95,0.99
  prometheus:
    metrics:
      export:
        enabled: true
